### ISSUE TITLE
Unicode issues

### ISSUE THREAD

**Issue by pswaminathan** [MediaMath/iq-get#3]
```
$ iq-get -d $'\t' myapikey 45174057
Traceback (most recent call last):
  File "/Users/pswaminathan/.virtualenvs/iqget/bin/iq-get", line 122, in <module>
    main(args)
  File "/Users/pswaminathan/.virtualenvs/iqget/bin/iq-get", line 107, in main
    write_final_output(out_file, delimiter, tmpFile)
  File "/Users/pswaminathan/.virtualenvs/iqget/bin/iq-get", line 71, in write_final_output
    writer.writerow(sl)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 58: ordinal not in range(128)
```

Am I doing something wrong?

**Comment by jwslocum** [comment]
Checkout my fork here: https://github.com/jwslocum/iq-get

Attached a script with encoding portion of script removed.
